name: Build

on:
  pull_request:
    branches:
      - next

jobs:

  build:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12, 14, 16, 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
